name: CI/CD for Calculator Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to project directory
        run: cd my-ts-project

      - name: Install dependencies
        working-directory: ./my-ts-library
        run: npm install

      - name: Run tests
        working-directory: ./my-ts-library
        run: npm test

      - name: Run SonarCloud analysis
        working-directory: ./my-ts-library
        run: sonar-scanner

      - name: Publish to npm
        working-directory: ./my-ts-library
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    
